
title = "Rodrigo Tributino Gonçalves"
author = "Rodrigo Tributino Gonçalves"
#copyright = "2020-2021"
description = "[Em construção]"
profilePicture = "images/Rodrigo.jpg"
keywords = ""
favicon = "icone/"
# example ["css/custom.css"]
#customCss = ["css/custom.css"]
# example ["js/custom.js"]
#customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
#readMore = true
#postSectionName = "blog"
contentratio = 0.7

[simpleAnalytics]
enable = true
use = "mathjax"
# customurl = "https://analytics.example.com"

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/rodrigo-tributino-goncalves/"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/rodrigotributino"

[[socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/rotributino_/"

[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:rotributino@gmail.com"

[[socialIcons]]
icon = "fab fa-skype"
title = "skype"
url = "https://join.skype.com/invite/rCJeXp2rrPyT"

[[socialIcons]]
icon = "fab fa-twitter"
title = "twitter"
url = "https://twitter.com/ro_tributino"

[[socialIcons]]
icon = "fab fa-kaggle"
title = "kaggle"
url = "https://www.kaggle.com/rodrigotributino"
