baseURL: https://rodrigotributino.github.io/blog/
languageCode: en
DefaultContentLanguage: en
title: Rodrigo Tributino Gonçalves
theme: anatole
summarylength: 10
enableEmoji: yes
enableRobotsTXT: yes
publishDir: docs
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
markup:
  goldmark:
    renderer:
      unsafe: yes
